services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=tjw'
      - 'MYSQL_PASSWORD=@abcd1234'
      - 'MYSQL_ROOT_PASSWORD=@abcd1234'
      - 'MYSQL_USER=user'
    ports:
      - '3307'
